### ISSUE TITLE
quote urls

### ISSUE THREAD

**Issue by ajs124** [svanderburg/pndp#1]
I noticed that composer2nix generates unquoted URLs, which at least in nixpkgs were deprecated with [RFC 45](https://github.com/NixOS/rfcs/pull/45).

A bit of digging leads me to believe that they get generated [here](https://github.com/svanderburg/pndp/blob/8cd8bc7a26306855426592afbb852e60ffcc5349/src/PNDP/AST/NixURL.php#L24). Would you accept a PR removing that case and always returning a quoted string?

**Comment by svanderburg** [comment]
Yes you're right that URL constructs should no longer be used. However, it should not be changed in PNDP, because its main purpose is to be a generator toolkit. NixURL is supposed to be semantically equivalent to a URL in the Nix expression language.

Instead, we should stop using the NixURL class in composer2nix. I have done that in this commit: https://github.com/svanderburg/composer2nix/commit/972f66ab44ed03a5d8de6d7f9e1041eeb8dd0f34 , which should solve the problem. You can give it a try by installing the development version.

I need solve another small issue in the code, then I'll make a new release.

**Comment by ajs124** [comment]
That does seem to work, yes.
